call plug#begin('~/.vim/plugged')
	Plug 'jalvesaq/Nvim-R', {'branch': 'stable'}
    Plug 'gruvbox-community/gruvbox'
	Plug 'davidhalter/jedi-vim'
    " Plug 'preservim/nerdtree'
call plug#end()

syntax on " syntax highlighting on 
set relativenumber " relative numbers on the left side of the screen
set number " absoute numbers on the left side of the screen
set nohlsearch " 
set hidden " does not force you to save a buffer to move away from you
set noerrorbells " no annoying sounds when you reach the end of the line
set tabstop=4 softtabstop=4 " 4 characters and 4 spaces for a tab respectively
set expandtab " tabs are filled with spaces
set shiftwidth=4
set smartindent " do the best job to indent for you 
set nowrap " let text flow off the screen
set smartcase " case sensitive search until you put a capital letter
set noswapfile " no vim.swap files in the project
set incsearch " get result WHILE you search

set colorcolumn=80 " vertical bar for when you are going horizontally too far
highlight ColorColumn ctermbg=0 guibg=lightgrey


imap jk <esc>

