set number
set relativenumber
imap jk <esc>

call plug#begin('~/.vim/plugged')
	Plug 'lervag/vimtex'
	let g:tex_flavor='latex'
	let g:vim_tex_view_method='zathura'
	let g:vim_tex_quickfix_mode=0
	set conceallevel=1
	let g:tex_conceal='abdmg'
	Plug 'jalvesaq/Nvim-R', {'branch': 'stable'}
	Plug 'davidhalter/jedi-vim'
        Plug 'junegunn/seoul256.vim'
        Plug 'preservim/nerdtree'
        " ...

call plug#end()
